spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/eduflow_db?currentSchema=elearningmanagerment"
    username: admin
    password: 123
  sql:
    init:
      mode: always # Luôn chạy file schema.sql khi khởi động dự án
  jpa:
    hibernate:
      # Vì ta đã tự viết SQL tạo bảng, nên để 'validate' để Hibernate kiểm tra xem
      # Model Java và Bảng dưới DB có khớp nhau không (tránh bị ghi đè lung tung)
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: elearningmanagerment